#Kotlin
kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx3072M
kotlin.parallel.tasks.in.project = true
kotlin.native.enableKlibsCrossCompilation=false
kotlin.native.ignoreDisabledTargets=true

#Gradle
org.gradle.jvmargs=-Xmx4096M -Dfile.encoding=UTF-8
org.gradle.configuration-cache=true
org.gradle.caching=true
org.gradle.paralle=true

#Android
android.nonTransitiveRClass=true
android.useAndroidX=true

kotlin.mpp.enableCInteropCommonization=true

#spm4kmp
spmforkmp.disableStartupFile=true
