#Kotlin
kotlin.code.style=official
# iOS release 프레임워크 링크(devirtualization 분석)가 3g로는 OOM 남
kotlin.daemon.jvmargs=-Xmx6g
kotlin.parallel.tasks.in.project = true
kotlin.native.enableKlibsCrossCompilation=false
kotlin.native.ignoreDisabledTargets=true

#Gradle
org.gradle.jvmargs=-Xmx4096M -Dfile.encoding=UTF-8
org.gradle.configuration-cache=true
org.gradle.caching=true
org.gradle.parallel=true

#Android
android.nonTransitiveRClass=true
android.useAndroidX=true

kotlin.mpp.enableCInteropCommonization=true

#spm4kmp
spmforkmp.disableStartupFile=true

# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
