[versions]
agp = "9.0.0"
android-compileSdk = "36"
android-minSdk = "28"
android-targetSdk = "36"
version-code = "2" # major(10), minor(01), patch(01), build(00)
version-name = "0.0.2" # major(1), minor(1), patch(1)

# Multiplatform
compose-multiplatform = "1.10.0"
kotlin = "2.3.20"
ksp = "2.3.4"

# androidX
androidx-core-ktx = "1.17.0"
androidx-appcompat = "1.7.1"
androidx-activityCompose = "1.12.2"
androidx-datastore = "1.2.0"
androidx-sqlite = "2.6.2"
androidx-room = "2.8.4"
androidx-credentials = "1.5.0"
androidx-startup = "1.2.0"
androidx-core-splashscreen = "1.0.1"

# org.jetbrains.kotlinx
kotlinx-coroutines = "1.10.2"
kotlinx-serialization = "1.10.0"
kotlinx-date-time = "0.7.1"
kotlinx-collections-immutable = "0.4.0"

# org.jetbrains.compose
compose-runtime = "1.10.0"
compose-ui = "1.10.0"
compose-foundation = "1.10.0"
compose-material3 = "1.10.0-alpha05"
compose-resources = "1.10.0"

# org.jetbrains.androidx
jetbrains-androidx-lifecycle = "2.10.0-alpha06"
jetbrains-androidx-navigation3-ui = "1.0.0-alpha06"
jetbrains-androidx-navigation3-event = "1.0.0"

# DI
koin = "4.2.1"
koin-compiler = "1.0.0-RC1"

# Network
ktor = "3.4.2"
ktorfit = "2.7.1"

# Image Loader
coil3 = "3.4.0"
compottie="2.2.2"

# Permission
moko = "0.20.1"

# Logging
napier = "2.7.1"

# Firebase
gms = "4.4.4"
firebase-bom = "34.8.0"
firebase-crahslytics = "3.0.6"

# Utility
kmp-spm = "1.8.0"
play-review = "2.0.2"
compose-stable-marker = "1.0.7"
build-konfig = "0.17.1"

# Test
turbine = "1.2.1"
mokkery = "3.3.0"
kotest = "6.1.1"
kover = "0.9.6"

# Lint
spotless = "8.2.1"
ktlint-cli = "1.8.0"
stability-analyzer = "0.7.2"

# Google Login
google-id = "1.2.0"

[libraries]
# androidX
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidx-core-ktx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidx-appcompat" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidx-activityCompose" }
androidx-datastore = { group = "androidx.datastore", name = "datastore", version.ref = "androidx-datastore" }
androidx-datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "androidx-datastore" }
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "androidx-room" }
androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "androidx-room" }
androidx-sqlite-bundled = { group = "androidx.sqlite", name = "sqlite-bundled", version.ref = "androidx-sqlite" }
androidx-credentials-credentials = { group = "androidx.credentials", name = "credentials", version.ref = "androidx-credentials" }
androidx-credentials-auth = { group = "androidx.credentials", name = "credentials-play-services-auth", version.ref = "androidx-credentials" }
androidx-startup = { group = "androidx.startup", name = "startup-runtime", version.ref = "androidx-startup" }
androidx-core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "androidx-core-splashscreen" }

# org.jetbrains.kotlinx
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
kotlinx-collections-immutable = { group = "org.jetbrains.kotlinx", name = "kotlinx-collections-immutable", version.ref = "kotlinx-collections-immutable" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
kotlinx-date-time = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "kotlinx-date-time" }

# org.jetbrains.compose
jetbrains-compose-runtime = { group = "org.jetbrains.compose.runtime", name = "runtime", version.ref = "compose-runtime" }
jetbrains-compose-ui = { group = "org.jetbrains.compose.ui", name = "ui", version.ref = "compose-ui" }
jetbrains-compose-ui-tooling = { group = "org.jetbrains.compose.ui", name = "ui-tooling", version.ref = "compose-ui" }
jetbrains-compose-ui-tooling-preview = { group = "org.jetbrains.compose.ui", name = "ui-tooling-preview", version.ref = "compose-ui" }
jetbrains-compose-foundation = { group = "org.jetbrains.compose.foundation", name = "foundation", version.ref = "compose-foundation" }
jetbrains-compose-material3 = { group = "org.jetbrains.compose.material3", name = "material3", version.ref = "compose-material3" }
jetbrains-compose-resources = { group = "org.jetbrains.compose.components", name = "components-resources", version.ref = "compose-resources" }

# org.jetbrains.androidx
jetbrains-androidx-lifecycle-viewmodel = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-viewmodel", version.ref = "jetbrains-androidx-lifecycle" }
jetbrains-androidx-lifecycle-viewmodel-savestate = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-viewmodel-savedstate", version.ref = "jetbrains-androidx-lifecycle" }
jetbrains-androidx-lifecycle-runtime-compose = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "jetbrains-androidx-lifecycle" }
jetbrains-androidx-lifecycle-viewmodel-nav3 = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-viewmodel-navigation3", version.ref = "jetbrains-androidx-lifecycle" }
jetbrains-androidx-navigation3-ui = { group = "org.jetbrains.androidx.navigation3", name = "navigation3-ui", version.ref = "jetbrains-androidx-navigation3-ui" }
jetbrains-androidx-navigation3-event = { group = "rg.jetbrains.androidx.navigationevent", name = "navigationevent-compose", version.ref = "jetbrains-androidx-navigation3-event" }

# DI
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-androidx-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "koin" }
koin-compose-viewmodel = { module = "io.insert-koin:koin-compose-viewmodel", version.ref = "koin" }
koin-compose-navigation3 = { group = "io.insert-koin", name = "koin-compose-navigation3", version.ref = "koin" }

# Network
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-client-auth = { module = "io.ktor:ktor-client-auth", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }

# Ktorfit
ktorfit-lib = { module = "de.jensklingenberg.ktorfit:ktorfit-lib", version.ref = "ktorfit" }
ktorfit-converters-response = { module = "de.jensklingenberg.ktorfit:ktorfit-converters-response", version.ref = "ktorfit" }
ktorfit-ksp = { module = "de.jensklingenberg.ktorfit:ktorfit-ksp", version.ref = "ktorfit" }

# Image Loader
coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil3" }
coil-compose-core = { module = "io.coil-kt.coil3:coil-compose-core", version.ref = "coil3" }
coil-network-ktor3 = { module = "io.coil-kt.coil3:coil-network-ktor3", version.ref = "coil3" }
coil-mp = { module = "io.coil-kt.coil3:coil", version.ref = "coil3" }
compottie = { module = "io.github.alexzhirkevich:compottie", version.ref = "compottie" }
compottie-lite = { module = "io.github.alexzhirkevich:compottie-lite", version.ref = "compottie" }
compottie-resources = { module = "io.github.alexzhirkevich:compottie-resources", version.ref = "compottie" }


# Logging
napier = { module = "io.github.aakira:napier", version.ref = "napier" }

# Permission
moko-permission-compose = { group = "dev.icerock.moko", name = "permissions-compose", version.ref = "moko" }
moko-permission-notifications = { group = "dev.icerock.moko", name = "permissions-notifications", version.ref = "moko" }

# Firebase
firebase-bom-android = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebase-bom" }
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics" }
firebase-crashlytics = { group = "com.google.firebase", name = "firebase-crashlytics" }
firebase-fcm = { group = "com.google.firebase", name = "firebase-messaging" }
firebase-auth = { group = "com.google.firebase", name = "firebase-auth" }

# Utility
play-review = { group = "com.google.android.play", name = "review-ktx", version.ref = "play-review" }
compose-stable-marker = { group = "com.github.skydoves", name = "compose-stable-marker", version.ref = "compose-stable-marker" }

# Test
turbine = { group = "app.cash.turbine", name = "turbine", version.ref = "turbine" }
kotest-assertions-core = { group = "io.kotest", name = "kotest-assertions-core", version.ref = "kotest" }
kotest-framework-engine = { group = "io.kotest", name = "kotest-framework-engine", version.ref = "kotest" }
kotest-runner-junit5 = { group = "io.kotest", name = "kotest-runner-junit5", version.ref = "kotest" }
kotest-extensions-koin = { group = "io.kotest", name = "kotest-extensions-koin", version.ref = "kotest" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
koin-test = { group = "io.insert-koin", name = "koin-test", version.ref = "koin" }
ktor-client-mock = { group = "io.ktor", name = "ktor-client-mock", version.ref = "ktor" }

# Gradle-Plugin
kotlin-gradleplugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
android-gradleplugin = { group = "com.android.tools.build", name = "gradle", version.ref = "agp" }
kotlin-serialization-gradleplugin = { group = "org.jetbrains.kotlin", name = "kotlin-serialization", version.ref = "kotlin" }
compose-compiler-gradleplugin = { group = "org.jetbrains.kotlin", name = "compose-compiler-gradle-plugin", version.ref = "kotlin" }
compose-multiplatform-gradleplugin = { group = "org.jetbrains.compose", name = "compose-gradle-plugin", version.ref = "compose-multiplatform" }
ksp-gradleplugin = { group = "com.google.devtools.ksp", name = "com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }
kover-gradleplugin = { group = "org.jetbrains.kotlinx", name = "kover-gradle-plugin", version.ref = "kover" }
stability-analyzer-gradleplugin = { group = "com.github.skydoves.compose.stability.analyzer", name = "com.github.skydoves.compose.stability.analyzer.gradle.plugin", version.ref = "stability-analyzer" }

# Google Id
android-google-id = { group = "com.google.android.libraries.identity.googleid", name = "googleid", version.ref = "google-id" }

[plugins]
# Android
android-application = { id = "com.android.application", version.ref = "agp" }
room = { id = "androidx.room", version.ref = "androidx-room" }

# KMP
android-kotlin-multiplatform-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
build-konfig = { id = "com.codingfeline.buildkonfig", version.ref = "build-konfig" }

# Compose
compose-multiplatform = { id = "org.jetbrains.compose", version.ref = "compose-multiplatform" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
compose-stability-analyzer = { id = "com.github.skydoves.compose.stability.analyzer", version.ref = "stability-analyzer" }

# Codegen
kmp-spm = { id = "io.github.frankois944.spmForKmp", version.ref = "kmp-spm" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }

# Google
google-services = { id = "com.google.gms.google-services", version.ref = "gms" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebase-crahslytics" }

# Test
mokkery = { id = "dev.mokkery", version.ref = "mokkery" }
spotless = { id = "com.diffplug.gradle.spotless", version.ref = "spotless" }
kotest = { id = "io.kotest", version.ref = "kotest" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }

# koin
koin-compiler = { id = "io.insert-koin.compiler.plugin", version.ref = "koin-compiler" }


[bundles]
ktor-client-plugin = [
    "ktor-client-content-negotiation",
    "ktor-client-auth",
    "ktor-client-logging",
]
moko = [
    "moko-permission-compose",
    "moko-permission-notifications"
]
datastore = [
    "androidx-datastore",
    "androidx-datastore-preferences"
]
build-logic-plugins = [
    "kotlin-gradleplugin",
    "kotlin-serialization-gradleplugin",
    "compose-compiler-gradleplugin",
    "compose-multiplatform-gradleplugin",
    "android-gradleplugin",
    "ksp-gradleplugin",
    "kover-gradleplugin",
    "stability-analyzer-gradleplugin",
]