name: Gradle Cache

on:
  push:
    branches:
      - develop

concurrency:
  group: gradle-cache-warm-${{ github.ref }}
  cancel-in-progress: true

jobs:
  gradle-cache:
    name: Gradle Cache
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set Up
        uses: ./.github/actions/ci/set-up
        with:
          local_properties: ${{ secrets.LOCAL_PROPERTIES }}
          google_services_json: ${{ secrets.GOOGLE_SERVICES_JSON }}
          keystore_base64: ${{ secrets.KEYSTORE_BASE64 }}
          cache_read_only: "false"

      - name: Warm tasks
        run: |
          ./gradlew \
            :androidApp:assembleDevDebug \
            test \
            --build-cache --parallel --stacktrace
