name: Slack Notifier

on:
  issue_comment:
    types: [created]

jobs:
  # ✅ 이슈 코멘트
  notify-issue-commented:
    if: |
      github.event_name == 'issue_comment' &&
      github.event.action == 'created' &&
      github.event.issue.pull_request == null &&
      github.event.comment.user.type != 'Bot'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/slack_notifier/comment/issue-comment
        with:
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}

  # ✅ PR 일반 코멘트
  notify-pr-general-commented:
    if: |
      github.event_name == 'issue_comment' &&
      github.event.action == 'created' &&
      github.event.issue.pull_request != null &&
      github.event.comment.user.type != 'Bot'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/slack_notifier/comment/pr-comment
        with:
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}

